version: "3"
services:
  petclinic_graphql_db:
    image: postgres:16.1-alpine
    command: ["postgres", "-c", "log_statement=all"]
    container_name: petclinic_graphql_db
    environment:
      - POSTGRES_PASSWORD=secretpw
      - POSTGRES_USER=klaus
      - POSTGRES_DB=petclinic_graphql_db
  petclinic_graphql_backend:
    image: spring-petclinic/petclinic-graphql-backend:0.0.1
    container_name: petclinic_graphql_backend
    depends_on:
      - petclinic_graphql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://petclinic_graphql_db:5432/petclinic_graphql_db
      - SPRING_DATASOURCE_USERNAME=klaus
      - SPRING_DATASOURCE_PASSWORD=secretpw
    ports:
      - "9977:9977"
