on:
  - push

jobs:
  petclinic-graphiql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./petclinic-graphiql

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm build
      - name: Copy to backend
        run: pnpm copy-to-backend

  backend:
    runs-on: ubuntu-latest
    needs: petclinic-graphiql
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with maven
        run: mvn -B package
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: petclinic-backend-jar
          path: ./backend/target/backend-0.0.1-SNAPSHOT.jar
          retention-days: 1

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install
#      - name: Run Codegen
#        run: pnpm run codegen
      - name: Code checks
        run: pnpm run check
      - name: Build application
        run: pnpm build
  end-to-end-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [petclinic-graphiql,backend,frontend]
    defaults:
      run:
        working-directory: ./e2e-tests
    steps:
      - name: setup playwright
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: LS
        run: ls -lR
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install JDK17
#        uses: actions/setup-java@v3
#        with:
#          java-version: "17"
#          distribution: "temurin"
#          cache: maven
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
